/*
 * Copyright (c) 2018, Intel Corporation.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _SHOW_PERFORMANCE_COMMAND_H_
#define _SHOW_PERFORMANCE_COMMAND_H_

#include <Uefi.h>

#define TARGET_PERFORMANCE_BYTES_READ_MASK	    0x1
#define TARGET_PERFORMANCE_BYTES_WRITTEN_MASK	0x2
#define TARGET_PERFORMANCE_HOST_READS_MASK		0x4
#define TARGET_PERFORMANCE_HOST_WRITES_MASK		0x8
#define TARGET_PERFORMANCE_BLOCK_READS_MASK		0x10
#define TARGET_PERFORMANCE_BLOCK_WRITES_MASK	0x20
#define TARGET_PERFORMANCE_ALL_MASK             TARGET_PERFORMANCE_BYTES_READ_MASK | TARGET_PERFORMANCE_BYTES_WRITTEN_MASK | \
                                                TARGET_PERFORMANCE_HOST_READS_MASK | TARGET_PERFORMANCE_HOST_WRITES_MASK | \
                                                TARGET_PERFORMANCE_BLOCK_READS_MASK | TARGET_PERFORMANCE_BLOCK_WRITES_MASK

#define TARGET_PERFORMANCE_BYTES_READ		L"BytesRead"
#define TARGET_PERFORMANCE_BYTES_WRITTEN	L"BytesWritten"
#define TARGET_PERFORMANCE_HOST_READS		L"HostReads"
#define TARGET_PERFORMANCE_HOST_WRITES		L"HostWrites"
#define TARGET_PERFORMANCE_BLOCK_READS		L"BlockReads"
#define TARGET_PERFORMANCE_BLOCK_WRITES		L"BlockWrites"


#define HELP_TEXT_PERFORMANCE_CATEGORIES   L""TARGET_PERFORMANCE_BYTES_READ \
										   L"|"TARGET_PERFORMANCE_BYTES_WRITTEN \
										   L"|"TARGET_PERFORMANCE_HOST_READS \
										   L"|"TARGET_PERFORMANCE_HOST_WRITES \
										   L"|"TARGET_PERFORMANCE_BLOCK_READS \
										   L"|"TARGET_PERFORMANCE_BLOCK_WRITES

#define PERFORMANCE_BYTES_READ_HEADER       L"DimmID\t"TARGET_PERFORMANCE_BYTES_READ L"\n"
#define PERFORMANCE_BYTES_WRITTEN_HEADER    L"DimmID\t"TARGET_PERFORMANCE_BYTES_WRITTEN L"\n"
#define PERFORMANCE_HOST_READS_HEADER       L"DimmID\t"TARGET_PERFORMANCE_HOST_READS L"\n"
#define PERFORMANCE_HOST_WRITES_HEADER      L"DimmID\t"TARGET_PERFORMANCE_HOST_WRITES L"\n"
#define PERFORMANCE_BLOCK_READS_HEADER      L"DimmID\t"TARGET_PERFORMANCE_BLOCK_READS L"\n"
#define PERFORMANCE_BLOCK_WRITES_HEADER     L"DimmID\t"TARGET_PERFORMANCE_BLOCK_WRITES L"\n"
#define PERFORMANCE_ALL_HEADER              L"DimmID\t"TARGET_PERFORMANCE_BYTES_READ L"\t\t"TARGET_PERFORMANCE_BYTES_WRITTEN L"\t\t" \
                                                       TARGET_PERFORMANCE_HOST_READS L"\t\t"TARGET_PERFORMANCE_HOST_WRITES L"\t\t" \
                                                       TARGET_PERFORMANCE_BLOCK_READS L"\t\t"TARGET_PERFORMANCE_BLOCK_WRITES L"\n"

#define PERFORMANCE_SINGLE_TARGET_FORMAT    L"0x%04x\t0x%08x%08x\n"
#define PERFORMANCE_ALL_FORMAT              L"0x%04x\t0x%08x%08x\t0x%08x%08x\t0x%08x%08x\t0x%08x%08x\t0x%08x%08x\t0x%08x%08x\n"

/**
Execute the Show Performance command

@param[in] pCmd command from CLI

@retval EFI_SUCCESS success
@retval EFI_INVALID_PARAMETER pCmd is NULL or invalid command line parameters
@retval EFI_NOT_READY Invalid device state to perform action
**/
EFI_STATUS
ShowPerformance(
	IN     struct Command *pCmd
);

/*
* Register the show dimms command
*/
EFI_STATUS
RegisterShowPerformanceCommand(
);

#endif //_SHOW_PERFORMANCE_COMMAND_H_
