/*
 * Copyright (c) 2020, Intel Corporation.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef _VERSION_OS_BUILD_H_
#define _VERSION_OS_BUILD_H_

#define NVMDIMM_RELEASE_TYPE        GENERAL_RELEASE

#define NVMDIMM_VERSION NVMDIMM_MAJOR_VERSION<<16 | \
  NVMDIMM_MINOR_VERSION<<8

#define NVMDIMM_VERSION_STRING DEFINE_TO_STRING(__VERSION_NUMBER__)
#define NVMDIMM_VERSION_STRING_A STRINGIZE(__VERSION_NUMBER__)

#endif /** _VERSION_OS_BUILD_H_ **/
